services:

  frontend:
    build: .
    container_name: BabyMonitor_Frontend
    ports:
      - "4200:80"
    networks: 
      - babymonitor-net 


networks:
  babymonitor-net :
    external: true
   


